Repository ejgallego/coq-serapi, pull requests merged in 2018-12, with the labels that each got.

#93 [test] Add test for setoid_rewrite tactic
  tests/genarg/dune
  tests/genarg/setoid_rewrite.v
Labels: bug, kind: testing

#94 [test] Add test case showing discrepancy between coqc and sercomp/compser
  tests/genarg/assoc.v
  tests/genarg/dune
Labels: bug, kind: testing

#95 [sercomp] Add check mode for compser
  CHANGES.md
  sertop/sercomp_lib.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
Labels: enhancement

#96 [sercomp] Add experimental `--quick` option to skip proofs.
  CHANGES.md
  sertop/sercomp_lib.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  tests/quick/ab.v
  tests/quick/assoc.v
  tests/quick/dune
Labels: enhancement, upstream

#99 [sercomp] Add --async-workers option to set max parallel jobs
  CHANGES.md
  sertop/sercomp_lib.ml
  sertop/sertop.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  sertop/sertop_async.ml
  sertop/sertop_init.ml
  sertop/sertop_init.mli
Labels: enhancement

#100 [doc] Add man pages with examples for sercomp and compser
  sertop/compser.ml
  sertop/sercomp.ml
  sertop/sercomp_lib.ml
  sertop/sercomp_lib.mli
Labels: for-doc

#102 [sercomp] Disable kernel safety check when in --quick mode.
  sertop/sercomp_lib.ml
Labels: upstream

#90 [test] Add test for abstract tactic
  tests/genarg/abstract.v
  tests/genarg/dune
Labels: bug, kind: testing, upstream

#105 [build] Update opam file with ocamlfind dependency
  coq-serapi.opam
Labels: kind: infrastructure

#106 [test] Add async test
  tests/async/dune
  tests/async/quote.v
Labels: bug, kind: testing, part: async

#107 [sertop] Adapt to mltop passing the full module path.
  sertop/sertop_init.ml
  sertop/sertop_loader.ml
Labels: upstream
