Repository ejgallego/coq-serapi, pull requests merged in 2018-11, with the labels that each got.

#71 [build] Build SerAPI with Dune.
  .gitignore
  .merlin
  .travis.yml
  CHANGES.md
  Makefile
  VERSION
  _tags
  config.mk
  coq-serapi.install
  coq-serapi.opam
  dune
  dune-project
  jscoq/coq-js/dune
  opam
  serapi/.merlin
  serapi/dune
  serlib/.merlin
  serlib/Makefile
  serlib/dune
  serlib/plugins/firstorder/.merlin
  serlib/plugins/firstorder/dune
  serlib/plugins/ltac/.merlin
  serlib/plugins/ltac/dune
  serlib/plugins/ssr/.merlin
  serlib/plugins/ssr/dune
  serlib/plugins/ssrmatching/dune
  serlib/ser_esubst.ml
  serlib/ser_esubst.mli
  serlib/ser_ppannotation.ml
  serlib/ser_ppannotation.mli
  sertex/.merlin
  sertex/dune
  sertop/.merlin
  sertop/dune
Labels: enhancement

#72 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: for-doc

#74 [serlib] add test for fix tactic
  tests/genarg/dune
  tests/genarg/fix.v
Labels: bug

#79 [serlib] add test for Hint Rewrite
  tests/genarg/dune
  tests/genarg/hint_rewrite.v
Labels: bug

#80 [serlib] test for Add Field
  tests/genarg/add_field.v
  tests/genarg/dune
Labels: bug

#81 [test] add test for intropatterns
  tests/genarg/dune
  tests/genarg/intropattern.v
Labels: bug

#78 [sercomp] Add option controlling output mode.
  CHANGES.md
  sertop/sercomp.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
Labels: enhancement

#83 [serlib] compser tool with failed deserialization example
  CHANGES.md
  sertop/compser.ml
  sertop/dune
  tests/genarg/dune
  tests/genarg/tactic_notation.v
Labels: bug, enhancement

#85 [sertop] Set Coq module name correctly from module file.
  CHANGES.md
  sertop/sertop_sexp.ml
  tests/genarg/dune
  tests/genarg/test_roundtrip
Labels: kind: testing

#88 [test] Add test for instantiate tactic
  tests/genarg/dune
  tests/genarg/instantiate.v
Labels: bug, kind: testing

#89 [test] Add test for functional induction tactic
  tests/genarg/dune
  tests/genarg/functional_induction.v
Labels: bug, kind: testing
