Repository ejgallego/coq-serapi, pull requests merged in 2019-03, with the labels that each got.

#121 [doc] Revise README.md to fix typos and omissions.
  README.md
Labels: for-doc

#120 [sercomp] Unify sercomp and compser by adding input option to sercomp
  CHANGES.md
  sertop/compser.ml
  sertop/dune
  sertop/sercomp.ml
  sertop/sercomp_lib.ml
  sertop/sercomp_lib.mli
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  tests/genarg/dune
  tests/genarg/test_roundtrip.in
Labels: enhancement, for-doc

#122 [js] [sertop] Remove warnings on newer APIs.
  jscoq/coq-js/jslib.ml
  jscoq/coq-js/jslib.mli
  jscoq/coq-js/jslibmng.ml
  sertop/sertop_js.ml
Labels: kind: infrastructure

#101 [test] Add two failing tests for --quick
  tests/quick/dune
  tests/quick/ordered.v
  tests/quick/reserved.v
Labels: bug, kind: testing

#125 [serapi] Make sure every command ends with `Completed`
  CHANGES.md
  serapi/serapi_protocol.ml
Labels: protocol

#126 [sercomp] Add `--mode=kexp` to output the final kernel environment.
  CHANGES.md
  sertop/sercomp.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
Labels: enhancement, kind: serialization

#127 [serlib] Serialize Opaqueproof.opaque
  CHANGES.md
  serlib/ser_future.ml
  serlib/ser_mod_subst.ml
  serlib/ser_mod_subst.mli
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_opaqueproof.ml
Labels: kind: serialization

#131 [serlib] Bugfix in Ser_entries.
  serlib/ser_entries.ml
  serlib/ser_safe_typing.ml
Labels: kind: serialization

#132 [serlib] Fix serialization for global_declaration
  CHANGES.md
  serlib/ser_cemitcodes.ml
  serlib/ser_cemitcodes.mli
  serlib/ser_declarations.mli
  serlib/ser_entries.ml
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_safe_typing.ml
  serlib/ser_safe_typing.mli
Labels: kind: serialization
