Repository ejgallego/coq-serapi, pull requests merged in 2019-10, with the labels that each got.

#179 [serlib] Fix ppx_import w.r.t. old-style pack plugin compilation
  .travis.yml
  coq-serapi.opam
  serlib/plugins/ltac/ser_tacentries.ml
  serlib/plugins/ltac/ser_tacenv.ml
  serlib/plugins/ssr/ser_ssrast.ml
  serlib/plugins/ssr/ser_ssrequality.ml
  serlib/plugins/ssr/wrap_ssrast.ml
Labels: kind: infrastructure

#181 [sertop] Add `--no_prelude` option
  CHANGES.md
  sertop/sertop.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  sertop/sertop_sexp.ml
  sertop/sertop_sexp.mli
Labels: kind: enhancement

#178 [doc] Mention new SerAPI applications in README.md
  README.md
Labels: kind: documentation

#182 [serlib] [serapi] Fix serialization of `MBId`, improve printing state.
  CHANGES.md
  Makefile
  README.md
  serapi/serapi_goals.ml
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  serlib/ser_names.ml
  sertop/sertop_ser.ml
  tests/genarg/dune
  tests/genarg/mbid.v
Labels: kind: bug, kind: serialization

#161 [sercomp] sertok program for batch tokenization
  CHANGES.md
  README.md
  sertop/dune
  sertop/sertok.ml
  sertop/sertop_ser.ml
  sertop/sertop_ser.mli
Labels: kind: enhancement, kind: serialization

#185 [doc] Metadata and documentation additions
  README.md
  coq-serapi.opam
Labels: kind: documentation

#186 [doc] Small README fixes and build instruction updates
  README.md
  notes/build.md
Labels: kind: documentation

#187 [serapi] Add string formatted messages to `CoqExn` and `Message`
  CHANGES.md
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  serlib/ser_feedback.mli
  sertop/sertop_async.ml
  sertop/sertop_ser.ml
  sertop/sertop_sexp.ml
  sertop/sertop_util.ml
  sertop/sertop_util.mli
Labels: kind: enhancement, protocol
