Repository ejgallego/coq-serapi, pull requests merged in 2019-06, with the labels that each got.

#163 [serapi] Pretty-print exceptions inside `CoqExn` answer.
  CHANGES.md
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  sertop/sertop_ser.ml
Labels: kind: enhancement, protocol

#165 Install the serapi and sertop sub-libraries
  serapi/dune
  sertop/dune
Labels: kind: infrastructure

#169 [serlib] Fix capitalization conventions for a few types in `Names`
  CHANGES.md
  serlib/ser_names.ml
Labels: kind: bug, kind: serialization

#168 [ci] Remove hacks now that ppx_deriving_yojson 3.4 is on OPAM.
  .travis.yml
Labels: kind: infrastructure

#170 [serapi] Add bullet suggestion information to goals
  CHANGES.md
  serapi/serapi_goals.ml
  serapi/serapi_goals.mli
Labels: protocol

#171 [serapi] Export get_goals_gen [used by jscoq]
  serapi/serapi_goals.mli
Labels: kind: enhancement
