Repository ejgallego/coq-serapi, pull requests merged in 2020-06, with the labels that each got.

#207 [sertop] Add sername program for serialization of terms
  .travis.yml
  CHANGES.md
  coq-serapi.opam
  dune-project
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  sertop/dune
  sertop/sername.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  sertop/sertop_ser.ml
  tests/sername/dune
  tests/sername/nat_add.out
  tests/sername/nat_add.sername
Labels: kind: enhancement, kind: serialization

#209 [sercomp] Forward port of sername
  .travis.yml
  CHANGES.md
  serapi/serapi_protocol.mli
  sertop/dune
  sertop/sername.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  tests/sername/dune
  tests/sername/nat_add.out
  tests/sername/nat_add.sername
Labels: kind: enhancement, kind: query

#211 [doc] Update README.md with additional clients of SerAPI
  README.md
Labels: kind: documentation

#213 [build] Require Dune >= 2.0
  CHANGES.md
  Makefile
  coq-serapi.opam
  dune-project
  sertop/dune
  tests/fail/dune
  tests/genarg/dune
  tests/quick/dune
  tests/sername/dune
Labels: kind: infrastructure

#214 [serlib] Fix segfault in univs.ml
  CHANGES.md
  serlib/ser_univ.ml
  tests/sername/dune
  tests/sertop/dune
  tests/sertop/full_env.in
Labels: kind: bug
