Repository ejgallego/coq-serapi, pull requests merged in 2021-02, with the labels that each got.

#229 Fix documentation link
  README.md
Labels: kind: bug, kind: documentation

#230 Allow printing goals with evars
  serapi/serapi_goals.ml
Labels: kind: bug

#210 [sertop] New `(Fork (fifo_in file) (fifo_out file))` command
  CHANGES.md
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  sertop/sercomp.ml
  sertop/sername.ml
  sertop/sertok.ml
  sertop/sertop_async.ml
  sertop/sertop_init.ml
  sertop/sertop_init.mli
  sertop/sertop_ser.mli
  sertop/sertop_sexp.ml
Labels: kind: enhancement, protocol
