Repository ejgallego/coq-serapi, pull requests merged in 2023-06, with the labels that each got.

#341 [ci] Fix 32bit gcc setup failure.
  .github/workflows/ci.yml
  coq-serapi.opam
  sertop/sertop_js.ml
Labels: kind: bug, kind: infrastructure

#343 [build] Rectypes are not needed in Coq anymore.
  dune
Labels: kind: upstream, kind: infrastructure

#344 Adapt w.r.t. coq/coq#17719.
  serlib/ser_vmvalues.ml
Labels: kind: upstream

#345 Adapt to coq/coq#17754
  serlib/ser_vernacexpr.ml
Labels: kind: upstream
