Repository ejgallego/coq-serapi, pull requests merged in 2023-02, with the labels that each got.

#304 Adapting to PR #16937 (that fixes recursive notation bug #12467).
  serlib/ser_extend.ml
  serlib/ser_notation_term.ml
  serlib/ser_notation_term.mli
Labels: kind: upstream

#318 [meta] Put SerAPI in maintenance mode.
  README.md
Labels: kind: meta, fixed by: flèche

#321 [serlib] [genarg] Fix Yojson serialization.
  CHANGES.md
  serlib/plugins/ltac/ser_tacarg.ml
  serlib/ser_genarg.ml
Labels: kind: bug, kind: enhancement, kind: serialization
