Repository ejgallego/coq-serapi, pull requests merged in 2023-01, with the labels that each got.

#298 Adapt w.r.t. coq/coq#17007.
  serlib/ser_declarations.ml
Labels: kind: upstream

#300 Adapt w.r.t. coq/coq#16910.
  tests/genarg/libTactics.v
Labels: kind: upstream

#305 adapt to coq/coq#16682
  notes/protocol.md
  serlib/ser_vernacexpr.ml
  serlib/ser_vernacexpr.mli
Labels: kind: upstream

#302 Adapt w.r.t. coq/coq#17053.
  serapi/serapi_goals.ml
Labels: kind: upstream

#306 [serlib] Support a few more plugins from Coq's stdlib.
  serlib/plugins/cc/dune
  serlib/plugins/micromega/dune
  serlib/plugins/syntax/dune
  serlib/plugins/syntax/ser_g_number_syntax.ml
  serlib/plugins/syntax/ser_number.ml
  serlib/plugins/tauto/dune
  serlib/plugins/zify/dune
  serlib/ser_constrexpr.ml
  serlib/ser_constrexpr.mli
  serlib/ser_notation.ml
  serlib/ser_notation.mli
  serlib/ser_numTok.ml
  sertop/sertop_loader.ml
Labels: kind: enhancement, kind: upstream, kind: serialization

#284 [serlib] Basic ltac2 support
  CHANGES.md
  serlib/plugins/ltac2/dune
  serlib/plugins/ltac2/ser_g_ltac2.ml
  serlib/plugins/ltac2/ser_tac2env.ml
  serlib/plugins/ltac2/ser_tac2expr.ml
  serlib/plugins/ltac2/ser_tac2quote.ml
  serlib/plugins/ssrmatching/ser_ssrmatching.ml
  serlib/ser_cEphemeron.ml
  serlib/ser_constr.ml
  serlib/ser_conv_oracle.ml
  serlib/ser_cooking.ml
  serlib/ser_declarations.ml
  serlib/ser_impargs.ml
  serlib/ser_mod_subst.ml
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_opaqueproof.ml
  serlib/ser_safe_typing.ml
  serlib/ser_tactypes.ml
  serlib/ser_util.ml
  serlib/ser_util.mli
  serlib/ser_vmemitcodes.ml
  sertop/sertop_loader.ml
Labels: kind: upstream, kind: serialization

#310 [forward port] Improvements from 0.16.2
  CHANGES.md
  Makefile
  serlib/plugins/cc/dune
  serlib/plugins/ltac2/dune
  serlib/plugins/ltac2/ser_g_ltac2.ml
  serlib/plugins/ltac2/ser_tac2env.ml
  serlib/plugins/ltac2/ser_tac2expr.ml
  serlib/plugins/ltac2/ser_tac2quote.ml
  serlib/plugins/micromega/dune
  serlib/plugins/ssrmatching/ser_ssrmatching.ml
  serlib/plugins/syntax/dune
  serlib/plugins/syntax/ser_g_number_syntax.ml
  serlib/plugins/syntax/ser_number.ml
  serlib/plugins/tauto/dune
  serlib/plugins/zify/dune
  serlib/ser_cEphemeron.ml
  serlib/ser_constr.ml
  serlib/ser_constrexpr.ml
  serlib/ser_constrexpr.mli
  serlib/ser_conv_oracle.ml
  serlib/ser_cooking.ml
  serlib/ser_declarations.ml
  serlib/ser_impargs.ml
  serlib/ser_mod_subst.ml
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_notation.ml
  serlib/ser_notation.mli
  serlib/ser_numTok.ml
  serlib/ser_opaqueproof.ml
  serlib/ser_safe_typing.ml
  serlib/ser_tactypes.ml
  serlib/ser_util.ml
  serlib/ser_util.mli
  serlib/ser_vmemitcodes.ml
  sertop/comp_common.ml
  sertop/comp_common.mli
  sertop/sercomp.ml
  sertop/sername.ml
  sertop/sertok.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  sertop/sertop_async.ml
  sertop/sertop_async.mli
  sertop/sertop_bin.ml
  sertop/sertop_init.ml
  sertop/sertop_init.mli
  sertop/sertop_js.ml
  sertop/sertop_loader.ml
  sertop/sertop_sexp.ml
  sertop/sertop_sexp.mli
Labels: kind: enhancement, kind: infrastructure

#308 [ci] Fix CI that was broken due to incomplete testing.
  .github/workflows/ci.yml
  sertop/sertop_async.ml
Labels: kind: infrastructure

#311 [forward port] Improvements from 0.16.2
  CHANGES.md
  serlib/plugins/cc/dune
  serlib/plugins/ltac2/dune
  serlib/plugins/ltac2/ser_g_ltac2.ml
  serlib/plugins/ltac2/ser_tac2env.ml
  serlib/plugins/ltac2/ser_tac2expr.ml
  serlib/plugins/ltac2/ser_tac2quote.ml
  serlib/plugins/micromega/dune
  serlib/plugins/ssrmatching/ser_ssrmatching.ml
  serlib/plugins/syntax/dune
  serlib/plugins/syntax/ser_g_number_syntax.ml
  serlib/plugins/syntax/ser_number.ml
  serlib/plugins/tauto/dune
  serlib/plugins/zify/dune
  serlib/ser_cEphemeron.ml
  serlib/ser_constr.ml
  serlib/ser_constrexpr.ml
  serlib/ser_constrexpr.mli
  serlib/ser_conv_oracle.ml
  serlib/ser_cooking.ml
  serlib/ser_declarations.ml
  serlib/ser_impargs.ml
  serlib/ser_mod_subst.ml
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_notation.ml
  serlib/ser_notation.mli
  serlib/ser_numTok.ml
  serlib/ser_opaqueproof.ml
  serlib/ser_safe_typing.ml
  serlib/ser_tactypes.ml
  serlib/ser_util.ml
  serlib/ser_util.mli
  serlib/ser_vmemitcodes.ml
  sertop/comp_common.ml
  sertop/comp_common.mli
  sertop/sercomp.ml
  sertop/sername.ml
  sertop/sertok.ml
  sertop/sertop_arg.ml
  sertop/sertop_arg.mli
  sertop/sertop_async.ml
  sertop/sertop_async.mli
  sertop/sertop_bin.ml
  sertop/sertop_init.ml
  sertop/sertop_init.mli
  sertop/sertop_js.ml
  sertop/sertop_loader.ml
  sertop/sertop_sexp.ml
  sertop/sertop_sexp.mli
Labels: kind: enhancement, kind: infrastructure

#309 [ci] Fix CI that was broken due to incomplete testing.
  .github/workflows/ci.yml
  Makefile
  sertop/sertop_async.ml
Labels: kind: infrastructure

#314 Adapt to coq/coq#17096 (detype isgoal argument is optional)
  sertop/sername.ml
Labels: kind: upstream

#307 Don't call init_known_plugins
  sertop/sertop_init.ml
Labels: kind: upstream
