Repository ejgallego/coq-serapi, pull requests merged in 2024-01, with the labels that each got.

#383 [serlib] Expose some more functions related to Require's AST.
  CHANGES.md
  serlib/ser_vernacexpr.mli
Labels: kind: enhancement, kind: serialization

#384 [ci] Remove obsolete pin on dune for Coq git build
  .github/workflows/ci.yml
Labels: kind: bug, kind: infrastructure

#376 Adapt to coq/coq#18327 (projection opacity)
  serlib/plugins/ltac/ser_tacexpr.ml
  serlib/ser_genredexpr.ml
  serlib/ser_names.ml
  serlib/ser_names.mli
  serlib/ser_tacred.ml
Labels: kind: upstream

#385 Adapt to coq/coq#18528 (profile_ltac moved to engine and renamed profile_tactic)
  serapi/serapi_protocol.ml
  serapi/serapi_protocol.mli
  serlib/ser_profile_tactic.ml
  serlib/ser_profile_tactic.mli
  sertop/sertop_ser.ml
Labels: kind: upstream
